# Generated by Django 4.1 on 2022-09-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(height_field=100, upload_to='projects/%Y-%m-%d/', width_field=100),
        ),
    ]
