# Generated by Django 4.1 on 2022-10-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(null=True, verbose_name='Ссылка на GitHub'),
        ),
    ]
