version: '3.7'
services:
  web:
    build: ./
    # restart: always
    command: gunicorn personal_portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - static_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pg_dumps:var.lib/postgresql/pg_dumps
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    ports:
      - 0.0.0.0:${DB_ONLINE_PORT}:5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - static_volume:/home/app/web/mediafiles
      - ./ssl/:/etc/nginx/ssl/
    ports:
      - ${WEB_SITE_PORT}:80
      - 443:443
    depends_on:
      - web
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
